### ISSUE TITLE
Too many bugs

### ISSUE THREAD

**Issue by vladimirmian** [null-none/ion-slider-range#1]
when i set the parameter like this:
<ionic-slider-range class="range-step" ng-step="100" ng-min="0" ng-max="3000" ng-model-min="from" ng-model-max="to"></ionic-slider-range>
$scope.from = 0;
$scope.to = 500;
It turns out:
two sliders ,and I can't slider the min slider on step 500

**Comment by null-none** [comment]
Please upload new version. Fixed all bugs + added example.

**Comment by null-none** [comment]
@vladimirmian fixed bugs.
